Quick Push 9fe4271cdc18208b48e3ba9d

diff --git a/bin/create-site-node b/bin/create-site-node
--- a/bin/create-site-node
+++ b/bin/create-site-node
@@ -78,6 +78,13 @@ then
   echo "This port is currently in use! Please select another port"
 fi
 
+if ! host $domain
+  then
+  echo "This is not a valid domain! Aborting!"
+  exit
+fi
+
+
 email=admin@$HOSTNAME
 
 ##Create user
diff --git a/bin/create-site-python b/bin/create-site-python
--- a/bin/create-site-python
+++ b/bin/create-site-python
@@ -86,6 +86,12 @@ then
   echo "This port is currently in use! Please select another port"
 fi
 
+if ! host $domain
+  then
+  echo "This is not a valid domain! Aborting!"
+  exit
+fi
+
 
 if [ -z "$python" ]
 then
