Quick Push b0a6e9a43ddf48a107c1f1af

diff --git a/bin/create-site-reverseproxy b/bin/create-site-reverseproxy
--- a/bin/create-site-reverseproxy
+++ b/bin/create-site-reverseproxy
@@ -85,6 +85,38 @@ user_password="$(openssl rand -hex 12)"
 bash create-linux-user -u $username -p $user_password
 
 
+
+## Setup a static HTML site for LetsEncrypt First
+nginx_vhost_file="/etc/nginx/sites-available/$username.conf"
+nginx_vhost_enabled="/etc/nginx/sites-enabled/$username.conf"
+cp "$template_path/nginx/basic/vhost.conf" $nginx_vhost_file
+
+sed -i "s/{{www_path}}/$(echo $www_path | sed 's/\//\\\//g')/" $nginx_vhost_file
+sed -i "s/{{domain}}/$domain/" $nginx_vhost_file
+sed -i "s/{{username}}/$username/g" $nginx_vhost_file
+sed -i "s/{{user_root}}/$(echo $chroot_home | sed 's/\//\\\//g')/" $nginx_vhost_file
+
+ln -s $nginx_vhost_file $nginx_vhost_enabled
+nginx -t && systemctl reload nginx
+
+
+## Test SSL Generation  
+if ! certbot certonly --dry-run --quiet --webroot -d $domain --non-interactive --agree-tos -m noamanahmed99@gmail.com -w $www_path
+then 
+echo "Error in certbot SSL generating. Cleaning up and aborting"
+delete-site -u $username -y --no_message
+exit 1;
+fi
+
+## Generate SSL
+certbot certonly --quiet --webroot -d $domain --non-interactive --agree-tos -m noamanahmed99@gmail.com -w $www_path
+
+
+## Removing Static site
+rm -rf $nginx_vhost_enabled
+rm -rf $nginx_vhost_file
+
+
 #Set up Nginx
 nginx_vhost_file="/etc/nginx/apps-available/reverseproxy.conf"
 nginx_vhost_enabled="/etc/nginx/apps-enabled/reverseproxy.conf"
