Quick Push 17491f5c5d74e18ab8e08449

diff --git a/bin/create-site-php b/bin/create-site-php
--- a/bin/create-site-php
+++ b/bin/create-site-php
@@ -212,16 +212,19 @@ nginx -t && systemctl reload nginx
 if [ -z "$nossl" ]
 then
 
-  ## Test SSL Generation
-  if ! certbot certonly --dry-run --quiet --webroot -d $domain --non-interactive --agree-tos -m $email -w $www_path
-  then 
-    echo "Error in certbot SSL generating. Cleaning up and aborting"
-    delete-site -u $username -y --no_message
-    exit 1;
+  ## Only Generate SSL If it is not already present. Timesave when re-creating sites
+  if [ ! -f "/etc/letsencrypt/live/$domain/fullchain.pem" ]
+  then
+    ## Test SSL Generation
+    if ! certbot certonly --dry-run --quiet --webroot -d $domain --non-interactive --agree-tos -m $email -w $www_path
+    then 
+      echo "Error in certbot SSL generating. Cleaning up and aborting"
+      delete-site -u $username -y --no_message
+      exit 1;
+    fi
+    ## Generate SSL
+    certbot certonly --quiet --webroot -d $domain --non-interactive --agree-tos -m $email -w $www_path
   fi
-  ## Generate SSL
-  certbot certonly --quiet --webroot -d $domain --non-interactive --agree-tos -m $email -w $www_path
-
   ## Enabling SSL in nginx settings
   sed -i "s/#SSL_DISABLED //" $nginx_vhost_file
   nginx -t && systemctl reload nginx    
