Quick Push 56079a976fc30c07aa50e416

diff --git a/bin/create-user-python b/bin/create-user-python
--- a/bin/create-user-python
+++ b/bin/create-user-python
@@ -11,15 +11,37 @@ if [ "$EUID" -ne 0 ]
   exit
 fi
 
-while getopts u:d:p:l:w: flag
-do
-    case "${flag}" in
-        u) username=${OPTARG};;        
-        d) domain=${OPTARG};;
-        p) php=${OPTARG};;
-        l) laravel=${OPTARG};;
-        w) wordpress=${OPTARG};;
-    esac
+
+while [ $# -gt 0 ]; do
+  case "$1" in
+    -u|--username)
+      username="$2"
+      shift
+      ;;
+    -d|--domain)
+      domain="$2"
+      shift
+      ;;
+    --mysql)
+      mysql=yes
+      ;;
+    --postgres)
+      postgres=yes
+      ;;
+    --mongodb)
+      mongodb=yes
+      ;;
+    --port)
+      port="$2"
+      shift
+      ;;    
+    *)
+      printf "***************************\n"
+      printf "* Error: Invalid argument. $1 *\n"
+      printf "***************************\n"
+      exit 1
+  esac  
+  shift
 done
 
 if [ -z "$username" ]
@@ -35,120 +57,110 @@ then
     exit
 fi
 
-
-if [ -z "$php" ]
-then
-php_version="7.4"
-else
-php_version=$php
-fi
-
-
 if id "$username" &>/dev/null
 then
-    echo "The $username already exists!. Please run delete-site -u $username"
+    echo "The $username already exists!. Please run delete-user -u $username"
     exit
 fi
 
-## Create system user if doesnt't exists
+if [ -z "$port" ] || [ $port -lt 1025 ] || [ $port -gt 65535 ]
+then
+  echo "Please specify a a valid port between 1025-65535 using --port for nginx to reverse proxy"
+  exit
+fi
 
-# $system_root="/home/$username";
-# mkdir -p $system_root
-# mkdir -p "$system_root/php/$php_version"
+if lsof -Pi :$port -sTCP:LISTEN -t >/dev/null
+then
+  echo "This port is currently in use! Please select another port"
+fi
 
 
 ##Create user
-pam-auth-update
-chmod 640 /etc/shadow
 user_password="$(openssl rand -hex 12)"
+bash create-linux-user -u $username -p $user_password
 
-adduser --gecos "" --disabled-password $username
-echo "$username:$user_password" | sudo chpasswd
+
+## Jail User for a php site
+bash jail-user -u $username -p yes
 
 ## Adding user to groups
 usermod -a -G web $username
 usermod -a -G sftp $username
 usermod -a -G $username nginx
+usermod -a -G $username nginx
 
 ## Create user directories
-user_root="/home/$username"
 
-mkdir -p $user_root
-mkdir -p "$user_root/logs"
-mkdir -p "$user_root/logs/nginx"
-mkdir -p "$user_root/logs/php"
-mkdir -p "$user_root/logs/mail"
-mkdir -p "$user_root/cache"
-mkdir -p "$user_root/cache/nginx"
+chroot_path=/var/www
+user_root=/home/$username
+chroot_home=$chroot_path/$user_root
 
-if [ -z "$laravel" ]
+mkdir -p $chroot_home
+mkdir -p $chroot_home/logs
+mkdir -p $chroot_home/logs/nginx
+mkdir -p $chroot_home/logs/python
+mkdir -p $chroot_home/cache
+mkdir -p $chroot_home/cache/nginx
+mkdir -p $chroot_home/www/
+
+www_path=$chroot_home/www
+mkdir -p $www_path
+
+## Fixing Permissions for nginx cache
+chown -R nginx:nginx $chroot_home/cache/nginx
+
+if [ -d "$mysql" ]
 then
-www_path=$user_root/www
-else
-mkdir -p $user_root/www/
-www_path=$user_root/www/public
+  ## Creating MYSQL user and database
+  database_name="$(echo $username | head -c 12)"
+  database_user="$(echo $username | head -c 12)"
+  database_password="$(openssl rand -hex 8)"
+
+  mysql -e "CREATE DATABASE IF NOT EXISTS $database_name"
+  mysql -e "DROP USER IF EXISTS '$database_user'@'localhost';"
+  mysql -e "CREATE USER '$database_user'@'localhost' IDENTIFIED BY '$database_password'"
+  mysql -e "GRANT ALL PRIVILEGES ON $database_name.* To '$database_user'@'localhost'"
+  mysql -e "GRANT SESSION_VARIABLES_ADMIN ON *.*  TO '$database_user'@'localhost'";
+  mysql -e "FLUSH PRIVILEGES;"
 fi
 
 
-#mkdir -p "$user_root/cache/php"
+## Setup a static HTML site for LetsEncrypt First
 
-## Fixing Permissions for nginx logs
-chown -R $username:$username $user_root/logs/php
-chown -R nginx:nginx $user_root/cache/nginx
-
-## Setting up default static HTML site
-mkdir -p $www_path
-cp $template_path/www/*.php $www_path/
-cp $template_path/www/*.html $www_path/
-
-## Creating PHP FPM Pool
-mkdir -p /opt/php-fpm/$username
-chown $username:$username /opt/php-fpm/$username
-
-## Setup all versions of pHP for quick switching(Needs to be optimized to allow one active PHP Versin per site/user)
-php_versions_array=("7.3" "7.4" "8.0" "8.1")
-
-for php_v in ${php_versions_array[@]}; do
-    sudo cp /etc/php/$php_v/fpm/pool.d/template.tpl /etc/php/$php_v/fpm/pool.d/$username.conf
-    sed -i "s/{{\$username}}/$username/" /etc/php/$php_v/fpm/pool.d/$username.conf
-    systemctl restart php$php_v-fpm
-done
-
-## Setup PHP-fpm for www
-ln -s /var/run/php/$username-$(echo "php$php" | sed 's/\.//')-fpm.sock /opt/php-fpm/$username/php-fpm.sock
-chown $username:$username /opt/php-fpm/$username/php-fpm.sock
-
-
-## Creating MYSQL user and database
-database_name="$(echo $username | head -c 12)"
-database_user="$(echo $username | head -c 12)"
-database_password="$(openssl rand -hex 8)"
-
-mysql -e "CREATE DATABASE IF NOT EXISTS $database_name"
-mysql -e "DROP USER IF EXISTS '$database_user'@'localhost';"
-mysql -e "CREATE USER '$database_user'@'localhost' IDENTIFIED BY '$database_password'"
-mysql -e "GRANT ALL PRIVILEGES ON $database_name.* To '$database_user'@'localhost'"
-mysql -e "GRANT SESSION_VARIABLES_ADMIN ON *.*  TO '$database_user'@'localhost'";
-mysql -e "FLUSH PRIVILEGES;"
-
-
-
-## Creating nginx settings
 nginx_vhost_file="/etc/nginx/sites-available/$username.conf"
 nginx_vhost_enabled="/etc/nginx/sites-enabled/$username.conf"
-cp "$template_path/nginx/vhost.conf" $nginx_vhost_file
+cp "$template_path/nginx/basic/vhost.conf" $nginx_vhost_file
 
 sed -i "s/{{www_path}}/$(echo $www_path | sed 's/\//\\\//g')/" $nginx_vhost_file
 sed -i "s/{{domain}}/$domain/" $nginx_vhost_file
 sed -i "s/{{username}}/$username/g" $nginx_vhost_file
-sed -i "s/{{user_root}}/$(echo $user_root | sed 's/\//\\\//g')/" $nginx_vhost_file
-sed -i "s/{{php_version}}/$php_version/" $nginx_vhost_file
+sed -i "s/{{user_root}}/$(echo $chroot_home | sed 's/\//\\\//g')/" $nginx_vhost_file
 
 ln -s $nginx_vhost_file $nginx_vhost_enabled
 nginx -t && systemctl reload nginx
 
 ## Generate SSL
 certbot certonly --quiet --webroot -d $domain --non-interactive --agree-tos -m noamanahmed99@gmail.com -w $www_path
+
+## Removing Static site
+rm -rf $nginx_vhost_enabled
+rm -rf $nginx_vhost_file
+
+
+
+## Creating nginx settings with reverse proxy
+nginx_vhost_file="/etc/nginx/sites-available/$username.conf"
+nginx_vhost_enabled="/etc/nginx/sites-enabled/$username.conf"
+cp "$template_path/nginx/python/vhost.conf" $nginx_vhost_file
+
+sed -i "s/{{www_path}}/$(echo $www_path | sed 's/\//\\\//g')/" $nginx_vhost_file
+sed -i "s/{{domain}}/$domain/" $nginx_vhost_file
+sed -i "s/{{username}}/$username/g" $nginx_vhost_file
+sed -i "s/{{user_root}}/$(echo $chroot_home | sed 's/\//\\\//g')/" $nginx_vhost_file
+sed -i "s/{{port}}/$port/" $nginx_vhost_file
+
+ln -s $nginx_vhost_file $nginx_vhost_enabled
+nginx -t && systemctl reload nginx
 
 ## Enabling SSL in nginx settings
 sed -i "s/#SSL_DISABLED //" $nginx_vhost_file
@@ -165,14 +177,19 @@ systemctl restart nginx
 mkdir -p /backups/$username
 chown -R $username:$username /backups/$username 
 
+## Installing nvm
+bash install-nvm -u $username
+
+
+##(TODO) Switch python version to the one specified 
+##bash toggle-python -u $username -p 
+
+##Copying demo app for simple proxy server
+cp $template_path/www/python/* $www_path/
+sed -i "s/{{port}}/$port/" $www_path/app.py
+
 ## Fixing permissions
 bash fix-permissions -u $username
-
-## Jail User for a php site
-bash jail-user -u $username -p yes
-
-## Switch php version to the one specified 
-bash toggle-python -u $username -p 3.0
 
 ## Setting up Logrotation
 bash logrotate-user -u $username -e yes
@@ -184,13 +201,24 @@ echo ""
 echo "Site Setup succssfull"
 echo "URL : http://$domain"
 echo "URL(SSL) : https://$domain"
-echo "Complete Path : $www_path"
+echo "Complete Path : /home/$username/www"
 echo ""
+if [ -d "$mysql" ]
+then
 echo ""
 echo "MySQL Database Credentials"
 echo "Database name: $database_name"
 echo "Database user: $database_user"
 echo "Database password: $database_password"
+fi
+if [ -d "$postgres" ]
+then
+echo ""
+echo "Postgres Database Credentials"
+echo "Database name: $database_name"
+echo "Database user: $database_user"
+echo "Database password: $database_password"
+fi
 echo ""
 echo "SFTP/SSH Details"
 echo "Host: $domain"
