Quick Push 7d3d5d5b15e1a31cf7836947

diff --git a/bin/create-postgres-db b/bin/create-postgres-db
--- a/bin/create-postgres-db
+++ b/bin/create-postgres-db
@@ -12,9 +12,9 @@ if [ "$EUID" -ne 0 ]
 fi
 
 
-if ! systemctl is-active --quiet postgres
+if ! systemctl is-active --quiet postgresql
   then 
-  echo "postgres is not running! Aborting!"
+  echo "postgresql is not running! Aborting!"
   exit
 fi
 
