Quick Push 86a20ff03520c16cabe908d9

diff --git a/bin/create-site-svelte b/bin/create-site-svelte
--- a/bin/create-site-svelte
+++ b/bin/create-site-svelte
@@ -108,7 +108,16 @@ ln -s $nginx_vhost_file $nginx_vhost_enabled
 nginx -t && systemctl reload nginx
 
 if [ -z "$nossl" ]
-then  
+then
+
+  ## Test SSL Generation  
+  if ! certbot certonly --dry-run --quiet --webroot -d $domain --non-interactive --agree-tos -m noamanahmed99@gmail.com -w $www_path
+  then 
+    echo "Error in certbot SSL generating. Cleaning up and aborting"
+    delete-site -u $username -y
+    exit 1;
+  fi
+    
   ## Generate SSL
   certbot certonly --quiet --webroot -d $domain --non-interactive --agree-tos -m noamanahmed99@gmail.com -w $www_path/public/
 
