Quick Push d61b31b26d4e4ea3dbe6eacf

diff --git a/bin/disable-monitor b/bin/disable-monitor
--- a/bin/disable-monitor
+++ b/bin/disable-monitor
@@ -69,5 +69,17 @@ api_request=$(curl -X POST -H "Cache-Control: no-cache" -H "Content-Type: applic
 -d "api_key=${uptime_robot_api_key}&format=json&id=${monitor_id}" \
 "https://api.uptimerobot.com/v2/deleteMonitor")
 
-echo $api_request
+
+api_status=$(echo $api_request | jq -r '.stat')
+
+if [ $api_status != "ok" ]
+then    
+  echo "API request Failed:"
+  echo "JSON Output:"
+  echo $api_request
+  exit 1
+fi
+
+
+rm -rf /var/www/home/$username/uptime_robot
 
