Quick Push 4d6ebc33a8d08f2845096de0

diff --git a/bin/enable-monitor b/bin/enable-monitor
--- a/bin/enable-monitor
+++ b/bin/enable-monitor
@@ -31,38 +31,52 @@ while [ $# -gt 0 ]; do
 done
 
 
-if [ -z "$username" ]
-then
-    echo "Please provide a username using -u "
-    exit
-fi
+# if [ -z "$username" ]
+# then
+#     echo "Please provide a username using -u "
+#     exit
+# fi
 
 
-if [ -z "$domain" ]
-then
-    echo "Please provide a domain using -d "
-    exit
-fi
+# if [ -z "$domain" ]
+# then
+#     echo "Please provide a domain using -d "
+#     exit
+# fi
 
 
-if ! id "$username" &>/dev/null
-then
-    echo "The $username already exists!. Please run delete-site -u $username"
-    exit
-fi
+# if ! id "$username" &>/dev/null
+# then
+#     echo "The $username already exists!. Please run delete-site -u $username"
+#     exit
+# fi
 
 
-uptime_robot_api_key=$(cat /opt/uptime_robot.key)
+# uptime_robot_api_key=$(cat /opt/uptime_robot.key)
 
-if [ -z "$uptime_robot_api_key" ]
+# if [ -z "$uptime_robot_api_key" ]
+# then    
+#   echo "Please set your main uptime robot key at /opt/uptime_robot.key to enable monitors"
+# fi
+
+
+# api_request=$(curl -X POST \
+# -H "Cache-Control: no-cache" -H "Content-Type: application/x-www-form-urlencoded" \
+# -d "api_key=$uptime_robot_api_key&format=json&type=1&url=https://$domain&friendly_name=$(hostname)_${username}_monitor" \
+# "https://api.uptimerobot.com/v2/newMonitor")
+api_request='{"stat":"ok","monitor":{"status":1,"id":791584464}}'
+
+api_status=$(echo $api_request | jq -r '.stat')
+
+if [ $api_status != "ok" ]
 then    
-  echo "Please set your main uptime robot key at /opt/uptime_robot.key to enable monitors"
+  echo "API request Failed:"
+  echo "JSON Output:"
+  echo $api_request
+  exit 1
 fi
 
-echo ""
-curl -X POST \
--H "Cache-Control: no-cache" -H "Content-Type: application/x-www-form-urlencoded" \
--d "api_key=$uptime_robot_api_key&format=json&type=1&url=https://$domain&friendly_name=$(hostname)_${username}_monitor" \
-"https://api.uptimerobot.com/v2/newMonitor"
+monitor_id=$(echo $api_request | jq -r '.monitor.id')
 
-echo ""
+echo monitor_id > /var/www/home/$username/uptime_robot
+
